### ISSUE TITLE
Epic / Procedure Editing

### ISSUE THREAD

**Issue by trisyoungs** [disorderedmaterials/dissolve#1176]
### Focus
Work towards full editability of `Procedure`s within the GUI.

#### Part 1
Implemented in #1177.
- [x] Refactor `ProcedureNodeStack` to bring in line with `ModuleControlWidget`-style operation and close #1171
#### Part 2
Implemented in #1180.
- [x] Retrofit `AnalyseModule` GUI to use a `ProcedureWidget`.
#### Part 3
Implemented in #1182.
- [x] Move model to produce a tree rather than a list.
#### Part 4
Implemented in #1224.
- [x] Don't require sequence nodes to store pointer to parent `Procedure`
- [x] Make `SequenceProcedureNode` a non-node class for use as a member variable.
#### Part 5
Implemented in #1225.
- [x] Allow drag/drop of nodes from a palette, similar to module layer editing.
- [x] Allow drag/drop reordering of nodes within a procedure
- [x] Allow renaming of nodes through model
- [x] Update `Procedure` after internal move to ensure validity of node keyword data
- [x] Fix internal move of root sequence nodes
#### Part 6
Implemented in #1238.
- [x] #923
- [x] Add controls to collapse / expand the tree
- [x] Add control to show/hide context column (hide by default too) to simplify view
- [x] Bug: OperateSitePopulationNormalise node appears to have no keywords
#### Part 7
- [x] Remove `ProcedureChart`, `MimeTreeWidget`, `MimeTreeWIdgetItem`, and `MimeStrings` classes (all defunct)
