### ISSUE TITLE
Code Tidy 2023

### ISSUE THREAD

**Issue by trisyoungs** [disorderedmaterials/dissolve#1415]
**Describe the feature / issue**
For readability it is well worth renaming many of our source files so they are not wholly lowercase names - for multi-part names something like `interactionPotential.h` is significantly more readable than `interactionpotential.h`.

At the same time, we could consider moving the `Configuration` and `Species` classes to their own separate source directory, since these two objects are quite significant pieces of the puzzle, and `src/classes` is getting rather large.

### Tasks
- [x] Use lowerCamelCase for all source files
- [x] ~Move `Configuration` class to its own directory~
- [x] ~Move `Species` class to its own directory~
- [x] Handle `SpeciesSite`, `SiteStack`, and `RemoveFragment` classes after merge of #1478.
- [x] ~Rename ANTLR4 files (currently uppercamelcase)~ Not a good idea, since this would enforce related class names into lowerCamelCase against the rest of the code's convention.
- [x] ~Query use of `src/gui/delegates/customcombodelegate.h`, and rename/remove as necessary.~ Still in use.
- [x] ~variantpointer.h still exists as a template?~ Still in use by two classes. Captured in #964
- [x] `io`
- [x] `ff`
