### ISSUE TITLE
Move to standard STL Containers

### ISSUE THREAD

**Issue by rprospero** [disorderedmaterials/dissolve#245]
Currently, the code base uses several custom container classes.  It may be possible to replace these with standard STL classes.  This will make it easier to on board new coders, lessen the code that needs to be maintained, and open up the possibility to use the STL library for further simplifications.

This will inherently be tied in with issue #244, since the current containers are also responsible for managing the memory at this time.

- [x] Array - could be std::vector
- [x] Array2d  - possibly an std::vector wrapper?
- [x] DynamicArray - could be std::deque
- [x] List - could be std::list
- [x] ParentList - Subclass of list that doesn't appear to be used anywhere in the code.
- [x] OrderedPointerArray - possibly an std::set, to keep the values ordered - #246
- [x] OrderedDAOArray - use whatever is chosen for OrderedPointerArray - #246
- [x] OrderedList - probably use std::set
- [x] OrdredPointerDataArray - Possible a std::vector of tuples.  Only used twice in the whole code base.
- [x] OrderedPointerList - use whatever is chosen for OrderedPointerArray
- [x] Pair - An std::pair of *optional* values.  This might require a little thought if we don't move to c++17.
- [x] PointerArray - probably an std::vector #240 
- [ ] RefList - Possibly a good choice to be replaced by std::list
- [x] RefDataList - Possibly a good choice to be replaced by std::list of tuples.

**Comment by rprospero** [comment]
Github jumped the gun on #948
