### ISSUE TITLE
Epic / 0.7 / UI Usability

### ISSUE THREAD

**Issue by trisyoungs** [disorderedmaterials/dissolve#319]
### Focus
Improvements to UI look and feel, and addressing of platform-dependent issues.

### Tasks
- [x] #231 Don't allow modules in separate tabs
- [x] #148 Display isotopologue selection on keyword button
- [ ] #163 HighDPI issues on Windows / OSX
- [x] #166 Reference data not updated in NeutronSQ
- [ ] #167 Viewer axis labels too small in HighDPI systems
- [x] #159 Indicate whether a layer is disabled on the icon
- [ ] #150 Iteration ETA is inaccurate
- [x] #195 Can't geometry minimise charged species
