### ISSUE TITLE
Epic / 0.7 / Data Management

### ISSUE THREAD

**Issue by trisyoungs** [disorderedmaterials/dissolve#324]
### Focus
Improved handling / management of generated data from within the GUI

### Tasks
- [x] #139 Protect data access by Renderables when simulation thread is active
- [x] #149 Clear specific Module data
- [x] #113 Module management should also manage associated data
