### ISSUE TITLE
Epic / Species Handling

### ISSUE THREAD

**Issue by trisyoungs** [disorderedmaterials/dissolve#380]
### Focus
Improves handling, editing, and general workflows associated with species.

### Tasks
- [ ] #301 Export Species
- [x] #316 Empirical formula of species not updated when deleting atoms
- [x] #214 Species editor widgets - remove medic widget, keep missing bonds
- [ ] #203 Add Hydrogens tool
- [x] #194 Create Species from existing Species
- [x] #186 Species editor Delete tool wrongly displays atom 
- [ ] #156 Allow undo/redo when editing species
- [x] #213 Species Viewer : remove missing bonds widget
- [ ] #234 Label atoms in SpeciesViewer
- [x] #637 Geometry minimise species when editing
- [ ] #636 Support creating / loading species from EPSR file formats
