### ISSUE TITLE
Update coordination number calculation

### ISSUE THREAD

**Issue by trisyoungs** [disorderedmaterials/dissolve#608]
The current coordination number module (`Calculate_CN`) has several issues:

1. Data is not saved to the restart file making it "GUI-only"
2. Although results are stored in `SampledDouble`s the calculation is made from `Calculate_RDF` module data which has already been averaged. This means that accumulating the coordination number data is effectively giving bogus statistics.

### Proposal

Move "trivial" coordination number calculation (with no statistical averaging) to `Calculate_RDF`, and reinvent `Calculate_CN` to be a proper averaging working on either the underlying RDF histogram, or calculating it for itself.

### Tasks

- [x] Publish `Sum1D` results in the restart file, as is done for `ProcessND`
- [x] ~`Sum1D` currently takes up to three ranges - reduce this to one and make it specific?~
- [x] Move trivial coordination number calculation to `Calculate_RDF`
- [x] Calculate CN statistics (i.e. histograms of CN)
- [x] #216
- [x] ~#151~
