### ISSUE TITLE
Epic / Bragg Scattering

### ISSUE THREAD

**Issue by trisyoungs** [disorderedmaterials/dissolve#643]
### Focus
Bring the (already present) Bragg scattering calculation back in line with the rest of the code.

### Tasks
- [ ] #276 

### To-Do
- [ ] Modernise relevant classes
- [ ] Add basic system test
- [ ] Add neutron system test (comparison with EPSR?)
- [ ] Implement / check broadening function consistent with EPSR
- [ ] Blending of intermediate region
