### ISSUE TITLE
Expand benchmark suite

### ISSUE THREAD

**Issue by StephenSmith25** [disorderedmaterials/dissolve#647]
### Focus
In #624 Google benchmarking was added to the project. This epic tracks the expansion of this benchmark suite.

### Tasks
- [ ] Extend problem benchmarking to include molecular systems
- [ ] Benchmark math files (e.g matrix and matrix operations, Fourier transform..)
- [ ] Benchmark templates e.g. vectors
- [ ] TBD

If you have any ideas for benchmarks please add them to the list.
